version: '3.1'

services:

    spring_db:
        image: postgres:16.1
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
            POSTGRES_DB: measdb
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        restart: unless-stopped

    mikrostoritev:
#        image: iideveloper21/measurements-qrks
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.jvm
        restart: unless-stopped
        ports:
            - 8280:8280
        environment:
            - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://spring_db:5432/measdb
            - QUARKUS_DATASOURCE_USERNAME=postgres
            - QUARKUS_DATASOURCE_PASSWORD=postgres
        depends_on:
            - spring_db

volumes:
    postgres:
